-- Mốc điện được đối chiếu lại tách riêng khỏi bill lịch sử.
-- Sửa mốc chỉ tác động bill từ ngày hiệu lực về sau, không thay đổi chứng từ cũ.

create table if not exists public.room_meter_baselines (
  id bigint generated by default as identity primary key,
  room_id bigint not null references public.rooms(id) on delete restrict,
  effective_from date not null,
  electricity_reading integer not null check (electricity_reading >= 0),
  note text,
  created_by bigint references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (room_id, effective_from)
);

create index if not exists room_meter_baselines_room_effective_idx
  on public.room_meter_baselines (room_id, effective_from desc);
